In [1]:
# Step 1 — Dataset

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

n = 1500

finance = pd.DataFrame({

"savings_balance": np.random.randint(5000,200000,n),

"salary": np.random.randint(2000,12000,n),

"debt": np.random.randint(0,150000,n),

"monthly_expense": np.random.randint(1000,7000,n)

})

finance.head()

   savings_balance  salary   debt  monthly_expense
0           191443   10667  84695             1865
1           126881   10308   5679             2509
2           125388    7352   8295             4421
3            27408   10174  43941             4669
4            17688    7356  14078             3051

In [2]:
# Step 2 — Scaling

scaler = StandardScaler()

scaled_data = scaler.fit_transform(finance)

In [3]:
# Step 3 — Clustering

from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=3)

finance["segment"] = kmeans.fit_predict(scaled_data)

finance.head()

   savings_balance  salary   debt  monthly_expense  segment
0           191443   10667  84695             1865        2
1           126881   10308   5679             2509        2
2           125388    7352   8295             4421        2
3            27408   10174  43941             4669        1
4            17688    7356  14078             3051        1

In [ ]:
# Step 4 — Visualization

import matplotlib.pyplot as plt
plt.scatter(finance["salary"],finance["savings_balance"],c=finance["segment"])

plt.xlabel("Salary")

plt.ylabel("Savings")

plt.title("Financial Wellbeing Segments")

plt.show()